[project]
name = "top-textbooks-service"
version = "0.0.1"
dependencies = [
    "flask",
    "python-dotenv",
    "requests",
]
[project.optional-dependencies]
test = [
    "debugpy",
    "pycodestyle",
    "pytest",
    "pytest-cov",
]
[project.scripts]
top-texbooks-service = "textbooks.server:run"
